### ISSUE TITLE
Slow Tokenized Timing out

### ISSUE THREAD

**Issue by Rahul12344** [ramanathanlab/genslm#84] opened 2023-01-27 19:24 UTC
**Describe the bug**

**To Reproduce**
1. Code with explanation
```
# from README of genslm
  
self.model = GenSLM("genslm_25M_patric", model_cache_dir="/home/ubuntu/genslm25M").to(self.device)
  
self.model.eval()

for i  in tqdm(range(0, len(sequences), 300)):        
    dataset = SequenceDataset(sequences[i:i+300], self.model.seq_length, self.model.tokenizer)
    dataloader = DataLoader(dataset)
    embeddings = []
    print(self.model.seq_length)
    with torch.no_grad():
           for batch in dataloader:
                  outputs = self.model(batch["input_ids"].to(self.device), batch["attention_mask"].to(self.device), output_hidden_states=True)
                  # outputs.hidden_states shape: (layers, batch_size, sequence_length, hidden_size)
                  emb = outputs.hidden_states[0].detach().cpu().numpy()
                  # Compute average over sequence length
                  emb = np.mean(emb, axis=1)
                  embeddings.append(emb)
```
3. How to run code
python [generate_genslm_embeddings].py

4. The error
The code times out after 252 sequences

**Expected behavior**
I have 27,000 short sequences of RNA - I expected a sizable percentage of them to have generated embeddings.

**Screenshots**
<img width="1196" alt="Screenshot 2023-01-27 at 2 23 36 PM" src="https://user-images.githubusercontent.com/9836445/215179126-266eba50-391f-4a6b-a1f9-a98c3e91af6f.png">

**Environment:
 - OS: Linux
 -  Package versions implicated in the error (torch, mdlearn versions, etc)
 - pytorch: 1.12.1
 - cudatoolkit: 11.6

**Additional context**

**Comment by braceal** [comment] 2023-01-28 06:16
Hi @Rahul12344, have you tried setting up the dataset/dataloader like this?

```python
self.model = GenSLM("genslm_25M_patric", model_cache_dir="/home/ubuntu/genslm25M").to(self.device)
  
self.model.eval()

dataset = SequenceDataset(sequences, self.model.seq_length, self.model.tokenizer)
dataloader = DataLoader(dataset, batch_size=128, drop_last=False)

print(f"Running inference with dataset length {len(dataloader)}") # Should print 27,000
      
embeddings = []
with torch.no_grad():
    for batch in dataloader:
        outputs = self.model(batch["input_ids"].to(self.device), batch["attention_mask"].to(self.device), output_hidden_states=True)
        # outputs.hidden_states shape: (layers, batch_size, sequence_length, hidden_size)
        emb = outputs.hidden_states[0].detach().cpu().numpy()
        # Compute average over sequence length
        emb = np.mean(emb, axis=1)
        embeddings.append(emb)
```

**Notes**
- `hidden_states[0]` specifies using hidden layer 0, you might try experimenting with other layers towards the middle of the model.
- After the code finishes you should have an embedding vector for each input sequence.

**Comment by Rahul12344** [comment] 2023-01-30 15:32
I haven't tried this, but I will soon and get back to this Issue! Thanks for the response.

**Comment by Rahul12344** [comment] 2023-01-30 15:55
Changed my code to 
```python 
dataset = SequenceDataset(sequences, self.model.seq_length, self.model.tokenizer)
dataloader = DataLoader(dataset, batch_size=64, drop_last=False)
```
but still got this issue:
<img width="333" alt="Screenshot 2023-01-30 at 10 55 40 AM" src="https://user-images.githubusercontent.com/9836445/215526993-8e35e1cd-c430-42aa-a391-46659132e1a6.png">
when tokenizing.

**Comment by braceal** [comment] 2023-02-03 23:01
Hi @Rahul12344 we just merged a bug fix. Can you try to run the installation command again and then give it another try?

**Comment by Rahul12344** [comment] 2023-02-10 17:42
The issue in https://github.com/ramanathanlab/genslm/issues/77 was resolved, but the tokenization is still getting killed!

**Comment by KPHippe** [comment] 2023-02-10 17:55
Hi @Rahul12344, is it possible to send us a small subset of the data to test on our end? We would like to recreate this bug on our systems if possible. Thanks!

**Comment by Rahul12344** [comment] 2023-02-17 16:33
Apologies for the delay - will send a subset ASAP

**Comment by Rahul12344** [comment] 2023-02-22 17:07
[aas copy.txt](https://github.com/ramanathanlab/genslm/files/10806496/aas.copy.txt)
[aar copy.txt](https://github.com/ramanathanlab/genslm/files/10806502/aar.copy.txt)

```python
def get_kmers_from_sequence(self, sequence, k=6):
        return ' '.join([sequence[i:i+k] for i in range(len(sequence)-k+1)])
```

**Comment by Rahul12344** [comment] 2023-02-22 17:07
Two example genomes; we generate kmers across the genome

**Comment by KPHippe** [comment] 2023-03-27 15:48
Hi @Rahul12344, sorry for the late reply. Unfortunately, our models only support tokenization using 3-mer's so unforunately this appears to be the cause for the failure. The tokenization process is inherently multi-threaded which can cause silent failures during processing. Feel free to try with `k=3` and let us know if the problem persists. Thanks!

**Closed** 2023-05-03 16:06 UTC
Labels: bug
